apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  destination:
    namespace: jenkins
    server: https://kubernetes.default.svc

  source:
    chart: jenkins
    repoURL: 'https://github.com/abdulrahmanalaa123/DEVOPS_CAPSTONE'
    path: jenkins/manifests
    targetRevision: jenkins
    helm:
      valueFiles:
      - jenkins/manifests/jenkins-values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
