installPlugins:
    - git
    - github
    - github-api
    - github-branch-source
    - docker-workflow
    - kubernetes
    - terraform
    - aws-java-sdk
    - credentials
    - plain-credentials
    - ssh-credentials
    - matrix-auth
    - configuration-as-code
    - pipeline-github-lib
    - antisamy-markup-formatter
    - mailer
    - ws-cleanup
    - workflow-job
    - workflow-cps
    - workflow-aggregator
    - pipeline-stage-view
    - workflow-basic-steps
    - workflow-durable-task-step
    - dark-theme

service:
  type: LoadBalancer
  port: 8080

resources:
  requests:
    cpu: "1000m"
    memory: "2048Mi"
  limits:
    cpu: "2000m"
    memory: "4096Mi"

controller.admin.createSecret: true
admin:
    createSecret: true
    username: "admin"
    password: "admin"


persistence:
  enabled: false
  storageClass: "gp2"
  size: "8Gi"
  accessModes:
    - ReadWriteOnce
  annotations: {}