# jenkins-values.yaml
controller:
  # Basic Configuration
  serviceType: LoadBalancer
  servicePort: 80
  jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"

  # Admin Credentials
  admin:
    username: "admin"
    password: "admin"

  # Persistence
  persistence:
    enabled: true
    size: 8Gi

  # Plugins (Required for Kubernetes agents)
  installPlugins:
    - kubernetes:1.31.4
    - workflow-aggregator:2.6
    - git:4.11.3
    - configuration-as-code:1.55
    - blueocean:1.25.8

  # JCasC Configuration for Kubernetes Agents
  JCasC:
    enabled: true
    configScripts:
      kubernetes-cloud: |
        jenkins:
          clouds:
            - kubernetes:
                name: "kubernetes"
                serverUrl: "https://kubernetes.default.svc"
                namespace: "jenkins-agents"
                jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
                podTemplates:
                  - name: "jnlp-agent"                                                   # jnlp container for jenkins connection 
                    label: "jenkins-agent"
                    containers:
                      - name: "jnlp"
                        image: "jenkins/inbound-agent:4.11-1-jdk11"
                        args: '${computer.jnlpmac} ${computer.name}'
                    volumes:v                                                            # Docker socket mount for containerized builds
                      - hostPathVolume:
                          hostPath: "/var/run/docker.sock"
                          mountPath: "/var/run/docker.sock"

  # Resource Limits
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

# Enable Kubernetes agent auto-scaling
agent:
  enabled: true
  podName: "jenkins-agent"
  customJenkinsLabels: "eks-agent"
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"